repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/golangci/golangci-lint
    rev: v1.36.0
    hooks:
    -   id: golangci-lint
# -   repo: https://github.com/tekwizely/pre-commit-golang
#     rev: v0.8.1
#     hooks:
#     # #
#     # # Go Build
#     # #
#     # -   id: go-build-mod
#     # -   id: go-build-pkg
#     # -   id: go-build-repo-mod
#     # -   id: go-build-repo-pkg
#     # #
#     # # Go Test
#     # #
#     # -   id: go-test-mod
#     # -   id: go-test-pkg
#     # -   id: go-test-repo-mod
#     # -   id: go-test-repo-pkg
#     # #
#     # # Go Vet
#     # #
#     # -   id: go-vet
#     # -   id: go-vet-mod
#     # -   id: go-vet-pkg
#     # -   id: go-vet-repo-mod
#     # -   id: go-vet-repo-pkg
#     # #
#     # # Formatters
#     # #
#     # -   id: go-fmt
#     # -   id: go-imports # replaces go-fmt
#     # -   id: go-returns # replaces go-imports & go-fmt
#     # #
#     # # Style Checkers
#     # #
#     # -   id: go-lint
#     # -   id: go-critic
#     # #
#     # # GolangCI-Lint
#     # # - Fast Multi-Linter
#     # # - Can be configured to replace MOST other hooks
#     # # - Supports repo config file for configuration
#     # # - https://github.com/golangci/golangci-lint
#     # #
#     -   id: golangci-lint
#     # -   id: golangci-lint-mod
#     # -   id: golangci-lint-pkg
#     # -   id: golangci-lint-repo-mod
#     # -   id: golangci-lint-repo-pkg
